AIRBO_HQ_STREET = ENV['AIRBO_HQ_STREET'] || '1702 Abbot Kinney Blvd'
AIRBO_HQ_CITY   = ENV['AIRBO_HQ_CITY']   || 'Venice'
AIRBO_HQ_STATE  = ENV['AIRBO_HQ_STATE']  || 'CA'
AIRBO_HQ_ZIP    = ENV['AIRBO_HQ_ZIP']    || '90291'
