STRIPE_PUBLIC_KEY  = ENV['STRIPE_API_PUBLIC_KEY']  || 'pk_test_oWRn7t2d9dB5Nwz2flmbzF74'
STRIPE_PRIVATE_KEY = ENV['STRIPE_API_PRIVATE_KEY'] || 'sk_test_xT46mncZ0N0zDnMZDqnPG9dI'
Stripe.api_key = STRIPE_PRIVATE_KEY
