STRIPE_PUBLIC_KEY  = ENV['STRIPE_API_PUBLIC_KEY']  || 'pk_test_YbL4xNmjGdb2HCHnYckEOBoE'
STRIPE_PRIVATE_KEY = ENV['STRIPE_API_PRIVATE_KEY'] || 'sk_test_kvoKVhLuoLbAisCpTDRdu6At'
Stripe.api_key = STRIPE_PRIVATE_KEY
