/* eslint-disable */
export const SET_USER_DATA = "SET_USER_DATA";

export const SET_ORGANIZATION_DATA = "SET_ORGANIZATION_DATA";

export const SET_PROGRESS_BAR_DATA = "SET_PROGRESS_BAR_DATA";
export const ADD_COMPLETION_AND_POINTS_TO_PROGRESS_BAR = "ADD_COMPLETION_AND_POINTS_TO_PROGRESS_BAR";

export const SET_TILES_DATA = "SET_TILES_DATA";
export const UPDATE_TILE_DATA = "UPDATE_TILE_DATA";
export const ADD_TILES_TO_STORE = "ADD_TILES_TO_STORE";
