fujifilm:
  name: FujiFilm
  logo: fuji_logo.png
  colorless_logo: fujifilm_logo_colorless.png
  headline: FujiFilm Loves Airbo
  background: fujifilm_wave.png
  link: fujifilm
  section:
    -
      subheader: FujiFilm and Airbo
      body:
        - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        - Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      quote:
        body: 450 diverse remote employees who could not communicate
        attribute: Jennifer Crick
    -
      subheader: Big Staff, Big Challenges
      body:
        - Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  featured_quote:
    body: Airbo has made is quicker and easier, and we're able to offer that prize element, which can really motivate people.
    attribute: HR Employee
    image: userpic.png
    index: 2

alta:
  name: Alta California
  logo: alta_logo.png
  colorless_logo: alta_logo_colorless.png
  headline: Learning How to Save Time and Communication
  background: alta_wave.png
  link: alta
  section:
    -
      subheader: Alta California Regional Center
      body:
        - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        - Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      quote:
        body: 450 diverse remote employees who could not communicate
        attribute: Jennifer Crick
    -
      subheader: Big Staff, Big Challenges
      body:
        - Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  featured_quote:
    body: Airbo has made is quicker and easier, and we're able to offer that prize element, which can really motivate people.
    attribute: HR Employee
    image: kate.jpg
    index: 2

asha:
  name: Asha California
  logo: asha_logo.png
  colorless_logo: asha_logo_colorless.png
  headline: Learning How to Save Time and Communication
  background: asha_wave.png
  link: asha
  section:
    -
      subheader: Alta California Regional Center
      body:
        - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        - Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      quote:
        body: 450 diverse remote employees who could not communicate
        attribute: Jennifer Crick
    -
      subheader: Big Staff, Big Challenges
      body:
        - Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  featured_quote:
    body: Airbo has made is quicker and easier, and we're able to offer that prize element, which can really motivate people.
    attribute: HR Employee
    image: kate.jpg
    index: 2

youthbuild:
  name: Youth Build
  logo: youthbuild_logo.png
  colorless_logo: youthbuild_logo_colorless.png
  headline: Learning How to Save Time and Communication
  background: youthbuild_wave.png
  link: youthbuild
  section:
    -
      subheader: Alta California Regional Center
      body:
        - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        - Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      quote:
        body: 450 diverse remote employees who could not communicate
        attribute: Jennifer Crick
    -
      subheader: Big Staff, Big Challenges
      body:
        - Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  featured_quote:
    body: Airbo has made is quicker and easier, and we're able to offer that prize element, which can really motivate people.
    attribute: HR Employee
    image: kate.jpg
    index: 2

rle:
  name: RLE Technologies
  logo: rle_logo.png
  colorless_logo: rle_logo_colorless.png
  headline: Learning How to Save Time and Communication
  background: rle_wave.png
  link: rle
  section:
    -
      subheader: Alta California Regional Center
      body:
        - Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
        - Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      quote:
        body: 450 diverse remote employees who could not communicate
        attribute: Jennifer Crick
    -
      subheader: Big Staff, Big Challenges
      body:
        - Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
  featured_quote:
    body: Airbo has made is quicker and easier, and we're able to offer that prize element, which can really motivate people.
    attribute: HR Employee
    image: kate.jpg
    index: 2
