#
# Format:
# 
# <heroku_san shorthand name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production: 
  app: hengage
  stack: bamboo-ree-1.8.7
  config: <<default

staging:
  stack: bamboo-ree-1.8.7
  app: hengage-staging
  config: &default
    BUNDLE_WITHOUT: "development:test"
