<% mongo_uri = ENV['MONGOHQ_URL'] || "mongodb://localhost:27017/health_#{Rails.env}" %>
<% parsed_mongo_uri = URI.parse(mongo_uri) %>

development: &default
  host: <%= parsed_mongo_uri.host %>
  port: <%= parsed_mongo_uri.port %>
  username: <%= parsed_mongo_uri.user %>
  password: <%= parsed_mongo_uri.password %>
  database: <%= parsed_mongo_uri.path.gsub(%r{^/}, '') %>

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
