<% mongo_uri = ENV['OLD_MONGO_URL'] || "mongodb://localhost:27017/health_#{Rails.env}" %>

development: &default
  sessions:
    default:
      uri: <%= mongo_uri %>

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
