Given /^the next random value generated by BonusThreshold out of (\d+) is rigged to be (\d+)$/ do |ceiling, points_to_award|
  ceiling = ceiling.to_i
  points_to_award = points_to_award.to_i

  BonusThreshold.any_instance.stubs(:rand).with(ceiling).returns(points_to_award)
end

