#!/bin/sh
RED="\x1b[31m"
GREEN="\x1b[32m"
COLOR_RESET="\x1b[0m"

echo_with_color() {
  echo "$2$1$COLOR_RESET"
}

BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [[ "$BRANCH" != "development" ]]; then
  echo_with_color 'You may only deploy to production from development.' $RED
  exit 1;
fi

read -p "Are you sure you want to deploy to production? " -r
echo
if [[ $REPLY =~ ^(yes|y| ) ]]
then
  echo_with_color "Deploying $(git rev-parse HEAD)" $GREEN

  git push production development:master
  heroku run rake db:migrate -a hengage
  heroku restart -a hengage

  echo_with_color "$(git rev-parse HEAD) deployed!" $GREEN

  echo_with_color "Setting Airbrake deploy" $GREEN
  ./script/airbrake_deploy_production
  echo
  echo_with_color "Deploy complete." $GREEN
else
  echo_with_color "Not deploying." $RED
fi
